backend:
  name: github
  repo: Builtbydesign/gaia-exclusive
  branch: main
  base_url: https://sveltia-cms-auth-worker.sveltia.workers.dev
  auth_endpoint: /auth/github

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
